version: '3'

services:
  # Directus CMS
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/database:/directus/database
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DB_CLIENT: "pg"
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      CORS_ENABLED: "true"
      CORS_ORIGIN: ${ALLOWED_ORIGINS}
      CACHE_ENABLED: "false"
      RATE_LIMITER_ENABLED: "false"
      
  # Mailhog для локальной отправки email
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP сервер
      - "8025:8025" # Веб-интерфейс
